services:
  credito: # <--- ESTE NOME TEM DE SER IGUAL AO DB_HOST DO .ENV!
    image: mysql:8.0
    container_name: meu_mysql
    env_file:
      - ./backend/.env
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - dados_mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${DB_PASS}"]
      interval: 5s
      timeout: 5s
      retries: 10

  api_backend:
    build: ./backend
    container_name: meu_backend
    restart: on-failure
    ports:
      - "5000:5000"
    # Adiciona esta linha abaixo para o Docker injetar o teu .env no container!
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/upload:/app/upload
      - ./backend/upload/comprovativos:/app/upload/comprovativos
    depends_on:
      credito:
        condition: service_healthy

  # 3. FRONTEND (React + Vite)
  web_frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules    # <-- Repare no espaço obrigatório depois do hífen
    depends_on:
      - api_backend

volumes:
  dados_mysql: # Garante que os dados do banco não sumam quando o container para